### ISSUE TITLE
Plugin crash with logzio_alert_v2 resource

### ISSUE THREAD

**Issue by smelchior** [logzio/terraform-provider-logzio#106]
When applying this example code the plugin crashes:
```
resource "logzio_alert_v2" "test" {
  title                          = "test"
  search_timeframe_minutes       = 5
  is_enabled                     = true
  alert_notification_endpoints   = [12345]
  suppress_notifications_minutes = 5
  output_type                    = "TABLE"
  sub_components {
    query_string                 = "*"
    should_query_on_all_accounts = true
    operation                    = "EQUALS"
    value_aggregation_type       = "COUNT"
    columns {
      field_name = "message"
    }
    severity_threshold_tiers {
      severity  = "HIGH"
      threshold = 10
    }
    severity_threshold_tiers {
      severity  = "INFO"
      threshold = 1
    }
  }
}
```

When running it without the sub_components.columns block + output_type set to JSON, it works without problems. Here is the trace:
```
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-logzio_v1.8.1 plugin:

panic: interface conversion: error is *errors.errorString, not alerts_v2.FieldError

goroutine 15 [running]:
github.com/logzio/logzio_terraform_provider/logzio.resourceAlertV2Update(0x14000278c40, 0x1033bf120, 0x140001badc0, 0x0, 0x0)
	github.com/logzio/logzio_terraform_provider/logzio/resource_alert_v2.go:333 +0x4a4
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x14000299b00, 0x140004285a0, 0x140001bb500, 0x1033bf120, 0x140001badc0, 0x103377f01, 0x140006e4f88, 0x1400026f6b0)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/resource.go:311 +0x1d4
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x1400021c580, 0x1400024d8d0, 0x140004285a0, 0x140001bb500, 0x1400025aaa8, 0x1400022c338, 0x103379b60)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/provider.go:294 +0x88
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x140001a8598, 0x1034a1070, 0x140000acc90, 0x140007683c0, 0x140001a8598, 0x102de9f38, 0x10340c5c0)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/helper/plugin/grpc_provider.go:885 +0x6cc
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1034472c0, 0x140001a8598, 0x1034a1070, 0x140000acc90, 0x14000768360, 0x0, 0x1034a1070, 0x140000acc90, 0x140001de400, 0x877)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000406160, 0x1034a87d8, 0x14000103200, 0x1400021e400, 0x140000ac510, 0x103944aa0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x380
google.golang.org/grpc.(*Server).handleStream(0x14000406160, 0x1034a87d8, 0x14000103200, 0x1400021e400, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xab0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0x14000758000, 0x14000406160, 0x1034a87d8, 0x14000103200, 0x1400021e400)
	google.golang.org/grpc@v1.23.0/server.go:710 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0x8c

Error: The terraform-provider-logzio_v1.8.1 plugin crashed!
```

**Comment by mirii1994** [comment]
I tried to recreate the issue, when I used your code sample got a different error, that was solved by adding to `sub_components.columns` a `sort` field . After that, it worked for me.
Can you try to add a `sort` field (allowed values are "ASC" or "DESC"), and let me know if this solved your issue?

```tf
resource "logzio_alert_v2" "test" {
  title                          = "test"
  search_timeframe_minutes       = 5
  is_enabled                     = true
  alert_notification_endpoints   = [12345]
  suppress_notifications_minutes = 5
  output_type                    = "TABLE"
  sub_components {
    query_string                 = "*"
    should_query_on_all_accounts = true
    operation                    = "EQUALS"
    value_aggregation_type       = "COUNT"
    columns {
      field_name = "message"
      sort = "ASC"
    }
    severity_threshold_tiers {
      severity  = "HIGH"
      threshold = 10
    }
    severity_threshold_tiers {
      severity  = "INFO"
      threshold = 1
    }
  }
}
```

**Comment by smelchior** [comment]
@mirii1994 thanks for getting back to me. Adding a sort field works for fields that are not analysed as text. In our case we would like to add the message field to the alert, which is an analysed field. In this case adding the sort parameter gets you this error:
```
{"errorCode":"Alerts/BAD_REQUEST","message":"Failed to create alert: Sorting is not allowed on analyzed fields","requestId":"7f9595b2-7388-48f0-ac4e-9876b7c592cf","parameters":{"reason":"Sorting is not allowed on analyzed fields","action":"CREATE"}}
```
Adding the a field without the sort param is possible in the API + Web interface, so it would be great if this is also available in the tf provider.

**Comment by mirii1994** [comment]
@smelchior v1.8.2 is out and should handle this.
Can you please confirm that your issue was resolved? :)

**Comment by smelchior** [comment]
@mirii1994 yes, works perfectly, thank you for the quick fix!
