### ISSUE TITLE
User update generated crash log

### ISSUE THREAD

**Issue by oleahy** [logzio/terraform-provider-logzio#29]
Created a new user using the logzio-terraform-provider, then tried to updated the user, changing the role from admin (3) to user (2). 

Terraform plan worked, but terraform apply caused a crash

Host is ubuntu xenial:
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

$ uname -r
4.4.0-159-generic

$ terraform -version
Terraform v0.12.7

terraform-provider-logzio was built from sources, head is:
$ git log -1
commit 47477a55fdc6c2b2dceb84eddf7297a81a447172
Author: jonboydell <jonboydell@hotmail.com>
Date:   Mon Aug 12 14:23:43 2019 +0100

    Update readme.md

The stack trace generated is below.

$ terraform apply -var="api_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -var="account_id=xxxxxxxxxx"  .
logzio_user.new_user: Refreshing state... [id=xxxxxx]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # logzio_user.new_user will be updated in-place
  ~ resource "logzio_user" "new_user" {
        account_id = xxxxxxxxxx
        active     = true
        fullname   = "another new user"
        id         = "xxxxxx"
      ~ roles      = [
          - 3,
          + 2,
        ]
        username   = "new.user@this.test"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

logzio_user.new_user: Modifying... [id=xxxxxx]

Error: rpc error: code = Unavailable desc = transport is closing

panic: interface conversion: interface {} is int, not string
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: goroutine 44 [running]:
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: github.com/jonboydell/logzio_terraform_provider/logzio.resourceUserUpdate(0xc000318e70, 0xf74aa0, 0xc000248de0, 0x24, 0x1ae40e0)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/tmp/logzio-scratch/logzio_terraform_provider/logzio/resource_user.go:121 +0x496
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00017cf80, 0xc0002929b0, 0xc00000e700, 0xf74aa0, 0xc000248de0, 0xc0001b7001, 0x1ab87f0, 0xf042a0)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/github.com/hashicorp/terraform@v0.12.6/helper/schema/resource.go:293 +0x264
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00017d000, 0xc0003fba58, 0xc0002929b0, 0xc00000e700, 0xc00021d048, 0xc000010260, 0xf06160)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/github.com/hashicorp/terraform@v0.12.6/helper/schema/provider.go:285 +0x18f
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0001744a0, 0x12cbd80, 0xc0001b6090, 0xc0000d9d40, 0xc0001744a0, 0xc0001b6090, 0xc000594bd0)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/github.com/hashicorp/terraform@v0.12.6/helper/plugin/grpc_provider.go:885 +0x894
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1028780, 0xc0001744a0, 0x12cbd80, 0xc0001b6090, 0xc000292730, 0x0, 0x12cbd80, 0xc0001b6090, 0xc000450420, 0x14e)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/github.com/hashicorp/terraform@v0.12.6/internal/tfplugin5/tfplugin5.pb.go:3217 +0x23e
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000572f00, 0x12d7da0, 0xc000573980, 0xc000167200, 0xc00016aea0, 0x1ab8c60, 0x0, 0x0, 0x0)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:966 +0x470
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: google.golang.org/grpc.(*Server).handleStream(0xc000572f00, 0x12d7da0, 0xc000573980, 0xc000167200, 0x0)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:1245 +0xd25
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00044a4a0, 0xc000572f00, 0x12d7da0, 0xc000573980, 0xc000167200)
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:685 +0x9f
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio: created by google.golang.org/grpc.(*Server).serveStreams.func1
2019-08-30T14:07:02.061+0100 [DEBUG] plugin.terraform-provider-logzio:  /home/ollie/new-work/pkg/mod/google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
2019-08-30T14:07:02.063+0100 [DEBUG] plugin: plugin process exited: path=/home/ollie/.terraform.d/plugins/terraform-provider-logzio pid=118181 error="exit status 2"
2019/08/30 14:07:02 [DEBUG] logzio_user.new_user: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/08/30 14:07:02 [TRACE] EvalWriteState: writing current state object for logzio_user.new_user
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2019/08/30 14:07:02 [TRACE] EvalApplyProvisioners: logzio_user.new_user is not freshly-created, so no provisioning is required
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/08/30 14:07:02 [TRACE] EvalWriteState: writing current state object for logzio_user.new_user
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalIf
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalIf
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2019/08/30 14:07:02 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/08/30 14:07:02 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/08/30 14:07:02 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/08/30 14:07:02 [TRACE] [walkApply] Exiting eval tree: logzio_user.new_user
2019/08/30 14:07:02 [TRACE] vertex "logzio_user.new_user": visit complete
2019/08/30 14:07:02 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/08/30 14:07:02 [TRACE] dag/walk: upstream of "provider.logzio (close)" errored, so skipping
2019/08/30 14:07:02 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/08/30 14:07:02 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2019/08/30 14:07:02 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2019/08/30 14:07:02 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2019/08/30 14:07:02 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/08/30 14:07:02 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-08-30T14:07:02.068+0100 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by oleahy** [comment]
main.tf:
variable "api_token" {
  type = "string"
  description = "your logzio API token"
} 
  
variable "account_id" {
  description = "the account id you want to use to create your user in"
}   

provider "logzio" {
  api_token = "${var.api_token}"
}

resource "logzio_user" "new_user" {
  username = "new.user@this.test"
  fullname = "another new user"
  roles = [ 2 ]
  account_id = "${var.account_id}"
}           

terraform.tfstate:
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 6,
  "lineage": "8a842b11-117d-6ec2-6638-4a15645d1008",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "logzio_user",
      "name": "new_user",
      "provider": "provider.logzio",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_id": xxxx,
            "active": true,
            "fullname": "another new user",
            "id": "364198",
            "roles": [
              3
            ],
            "username": "new.user@this.test"
          }
        }
      ]
    }
  ]
}

terraform.tfstate.backup
{
  "version": 4,
  "terraform_version": "0.12.7",
  "serial": 5,
  "lineage": "8a842b11-117d-6ec2-6638-4a15645d1008",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "logzio_user",
      "name": "new_user",
      "provider": "provider.logzio",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_id": xxxx,
            "active": true,
            "fullname": "another new user",
            "id": "364198",
            "roles": [
              3
            ],
            "username": "new.user@this.test"
          },
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}

**Comment by jonboydell** [comment]
Trying to repro on Xenial, can't repro on OSX

**Comment by sandermvanvliet** [comment]
I have reproduced this issue with version 1.4.0 of the provider after first performing a `terraform import` with the user resource defined like so:

```terraform
resource "logzio_user" "joe_blogs" {
  username = "joe.blogs@tempuri.org"
  fullname = "Joe Blogs"
  roles = [ 2 ]
  account_id = var.account_id
}
```
ran `terraform import logzio_user.joe_blogs 12345`

then changed definition to:

```terraform
resource "logzio_user" "joe_blogs" {
  username = "joe.blogs@tempuri.org"
  fullname = "Joe Blogs (Changed)"
  roles = [ 2 ]
  account_id = var.account_id
}
```

and ran `terraform apply -target=logzio_user.joe_blogs`
and got this stack trace:

```
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-logzio_v1.4.0 plugin:

panic: interface conversion: interface {} is int, not string

goroutine 44 [running]:
github.com/logzio/logzio_terraform_provider/logzio.resourceUserUpdate(0xc000137ea0, 0xed8c80, 0xc0005b06a0, 0x24, 0x193bdc0)
        github.com/logzio/logzio_terraform_provider/logzio/resource_user.go:124 +0x486
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00017d480, 0xc0003101e0, 0xc000786600, 0xed8c80, 0xc0005b06a0, 0xe7fc01, 0xc0002eb760, 0xc000316690)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/resource.go:311 +0x263
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00017d900, 0xc0002eb8e0, 0xc0003101e0, 0xc000786600, 0xc00030fca8, 0xc00010ec90, 0xe81880)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00010eab8, 0x121caa0, 0xc000301410, 0xc000051c20, 0xc00010eab8, 0xc000301410, 0xc0002e6a48)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xf8a860, 0xc00010eab8, 0x121caa0, 0xc000301410, 0xc000051bc0, 0x0, 0x121caa0, 0xc000301410, 0xc000132840, 0x15f)
        github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014a000, 0x1226840, 0xc000683c80, 0xc0001c0300, 0xc00018ae70, 0x1901980, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00014a000, 0x1226840, 0xc000683c80, 0xc0001c0300, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001023f0, 0xc00014a000, 0x1226840, 0xc000683c80, 0xc0001c0300)
        google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xa1

Error: The terraform-provider-logzio_v1.4.0 plugin crashed!
```

The output of `terraform apply` shows this before asking for confirmation:

```
  # logzio_user.sander_vanvliet will be updated in-place
  ~ resource "logzio_user" "joe_blogs" {
      ~ fullname   = "Joe Blogs" -> "Joe Blogs (Changed)"
        id         = "67757"
        # (4 unchanged attributes hidden)
    }
```
which shows a string for `id` where according to the code and the error stack trace it should be an `int`

**Comment by mirii1994** [comment]
The resource was refactored in the latest provider version (v1.10.0).
Please upgrade to it, and if an issue occurs, let us know :)
