### ISSUE TITLE
Custom alert notification endpoint - terraform crashes after creation

### ISSUE THREAD

**Issue by tomaszgawlik** [logzio/terraform-provider-logzio#58]
**Problem:** 
I'm trying to create new notification endpoint. This works fine but after that `terraform plan/apply` command crashes. 
Not sure if it's important, but maybe worth noteing that my Logz.io account is located in Europe. 
**Versions:**
Terraform v0.14.4
+ provider registry.terraform.io/logzio/logzio v1.1.7

**main.tf:**
```
terraform {
  required_providers {
    logzio = {
      source = "logzio/logzio"
      version = "1.1.7"
    }
  }
}

provider "logzio" {
  api_token = "TODO"
  region    = "eu"
}

resource "logzio_endpoint" "logz" {
  title = "title-demo"
  endpoint_type = "custom"
  description = "Managed by terraform"

  custom {
    url = "https://api.eu.opsgenie.com/v2/alerts"
    method = "POST"
    headers = {
        Content-Type= "application/json"
        Authorization= "GenieKey TODO"
    } 

    body_template = {
        message= "{{alert_title}}"
    }
  }
}
```

**How to reproduce:**
1. terraform init
2. terraform apply (this will create new endpoint)
3. terraform plan -> crashes

```
terraform plan  
logzio_endpoint.logz: Refreshing state... [id=27906]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [1] with length 1
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: goroutine 42 [running]:
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/logzio/logzio_terraform_client/endpoints.jsonEndpointToEndpoint(0xc000189470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  github.com/logzio/logzio_terraform_client@v1.3.1/endpoints/client_endpoints.go:91 +0xb33
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/logzio/logzio_terraform_client/endpoints.(*EndpointsClient).GetEndpoint(0xc00019e480, 0x6d02, 0x0, 0x0, 
0xc00019e480)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  github.com/logzio/logzio_terraform_client@v1.3.1/endpoints/client_endpoints_get.go:57 +0x16c
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/logzio/logzio_terraform_provider/logzio.resourceEndpointRead(0xc00035ec40, 0xf2c060, 0xc00028c3c0, 0xc00035ec40, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  github.com/logzio/logzio_terraform_provider/logzio/resource_endpoint.go:285 +0xa6
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000210f80, 0xc0002d9130, 0xf2c060, 0xc00028c3c0, 0xc00019e478, 0x0, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  github.com/hashicorp/terraform@v0.12.6/helper/schema/resource.go:437 +0x120
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0002084c8, 0x126a760, 0xc00013ec60, 0xc0002d8f50, 0xc0002084c8, 0xc00013ec60, 0xc0002e7a48)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  github.com/hashicorp/terraform@v0.12.6/helper/plugin/grpc_provider.go:525 +0x3df
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0xfdeb20, 0xc0002084c8, 0x126a760, 0xc00013ec60, 0xc0002d8f00, 0x0, 0x126a760, 0xc00013ec60, 0xc0000c26e0, 0x14f)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  github.com/hashicorp/terraform@v0.12.6/internal/tfplugin5/tfplugin5.pb.go:3181 +0x21e
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000704480, 0x12754e0, 0xc000704d80, 0xc000292f00, 0xc000486c60, 0x196c8d0, 0x0, 0x0, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  google.golang.org/grpc@v1.18.0/server.go:966 +0x471
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: google.golang.org/grpc.(*Server).handleStream(0xc000704480, 0x12754e0, 0xc000704d80, 0xc000292f00, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  google.golang.org/grpc@v1.18.0/server.go:1245 +0xca5
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000030290, 0xc000704480, 0x12754e0, 0xc000704d80, 0xc000292f00)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  google.golang.org/grpc@v1.18.0/server.go:685 +0xa8
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe:  google.golang.org/grpc@v1.18.0/server.go:683 +0xa8
2021/01/11 15:28:52 [TRACE] vertex "logzio_endpoint.logz": visit complete
2021/01/11 15:28:52 [TRACE] vertex "logzio_endpoint.logz": dynamic subgraph encountered errors
2021/01/11 15:28:52 [TRACE] vertex "logzio_endpoint.logz": visit complete
2021/01/11 15:28:52 [TRACE] vertex "logzio_endpoint.logz (expand)": dynamic subgraph encountered errors
2021/01/11 15:28:52 [TRACE] vertex "logzio_endpoint.logz (expand)": visit complete
2021/01/11 15:28:52 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/11 15:28:52 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/logzio/logzio\"] (close)" errored, so skipping
2021/01/11 15:28:52 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/11 15:28:52 [INFO] backend/local: plan operation completed
2021/01/11 15:28:52 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/01/11 15:28:52 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
2021-01-11T15:28:52.230Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/logzio/logzio/1.1.7/windows_amd64/terraform-provider-logzio_v1.1.7.exe pid=7988 error="exit status 2"
2021-01-11T15:28:52.230Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

from crash log:
```
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: panic: runtime error: index out of range [1] with length 1
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: goroutine 42 [running]:
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/logzio/logzio_terraform_client/endpoints.jsonEndpointToEndpoint(0xc000189470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	github.com/logzio/logzio_terraform_client@v1.3.1/endpoints/client_endpoints.go:91 +0xb33
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/logzio/logzio_terraform_client/endpoints.(*EndpointsClient).GetEndpoint(0xc00019e480, 0x6d02, 0x0, 0x0, 0xc00019e480)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	github.com/logzio/logzio_terraform_client@v1.3.1/endpoints/client_endpoints_get.go:57 +0x16c
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/logzio/logzio_terraform_provider/logzio.resourceEndpointRead(0xc00035ec40, 0xf2c060, 0xc00028c3c0, 0xc00035ec40, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	github.com/logzio/logzio_terraform_provider/logzio/resource_endpoint.go:285 +0xa6
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000210f80, 0xc0002d9130, 0xf2c060, 0xc00028c3c0, 0xc00019e478, 0x0, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	github.com/hashicorp/terraform@v0.12.6/helper/schema/resource.go:437 +0x120
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0002084c8, 0x126a760, 0xc00013ec60, 0xc0002d8f50, 0xc0002084c8, 0xc00013ec60, 0xc0002e7a48)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	github.com/hashicorp/terraform@v0.12.6/helper/plugin/grpc_provider.go:525 +0x3df
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler(0xfdeb20, 0xc0002084c8, 0x126a760, 0xc00013ec60, 0xc0002d8f00, 0x0, 0x126a760, 0xc00013ec60, 0xc0000c26e0, 0x14f)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	github.com/hashicorp/terraform@v0.12.6/internal/tfplugin5/tfplugin5.pb.go:3181 +0x21e
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000704480, 0x12754e0, 0xc000704d80, 0xc000292f00, 0xc000486c60, 0x196c8d0, 0x0, 0x0, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	google.golang.org/grpc@v1.18.0/server.go:966 +0x471
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: google.golang.org/grpc.(*Server).handleStream(0xc000704480, 0x12754e0, 0xc000704d80, 0xc000292f00, 0x0)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	google.golang.org/grpc@v1.18.0/server.go:1245 +0xca5
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000030290, 0xc000704480, 0x12754e0, 0xc000704d80, 0xc000292f00)
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	google.golang.org/grpc@v1.18.0/server.go:685 +0xa8
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-11T15:28:52.221Z [DEBUG] plugin.terraform-provider-logzio_v1.1.7.exe: 	google.golang.org/grpc@v1.18.0/server.go:683 +0xa8
```

**Comment by yyyogev** [comment]
Hi @tomaszgawlik 
Thanks for letting us know, we will check it out soon

**Comment by yyyogev** [comment]
Fixed at #72

**Comment by yyyogev** [comment]
Fixed at #62

**Comment by mirii1994** [comment]
Hi @tomaszgawlik did this fix help with your issue?

**Comment by Doron-Bargo** [comment]
Hi @tomaszgawlik ? 
Did you had time to check this fix?

**Comment by tomaszgawlik** [comment]
I'm really sorry, but I somehow haven't received any notification about this issue. I will check this very soon!

**Comment by tomaszgawlik** [comment]
it works now, thank you!
