### ISSUE TITLE
[BUG] data source logzio_endpoint crash

### ISSUE THREAD

**Issue by Veluu** [logzio/terraform-provider-logzio#65]
Hey

I defined single data soure as follows

`data "logzio_endpoint" "slack" {
  id = 14863
}
`

I have a valid api token.

```
terraform plan -var api_token=my-token
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.logzio_endpoint.slack: Refreshing state...

Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is int, not int64
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: goroutine 13 [running]:
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: github.com/logzio/logzio_terraform_provider/logzio.dataSourceEndpointRead(0xc0003020e0, 0xf27fe0, 0xc000506380, 0xc0003020e0, 0x0)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	github.com/logzio/logzio_terraform_provider/logzio/datasource_endpoint.go:31 +0x64d
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc000284a00, 0xc0006dd280, 0xf27fe0, 0xc000506380, 0xc000479680, 0x1, 0x0)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	github.com/hashicorp/terraform@v0.12.6/helper/schema/resource.go:380 +0x88
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc000285100, 0xc0006e1990, 0xc0006dd280, 0xc0006dd280, 0x0, 0x0)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	github.com/hashicorp/terraform@v0.12.6/helper/schema/provider.go:442 +0x8f
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000e4d0, 0x12735e0, 0xc00018cc30, 0xc000282600, 0xc00000e4d0, 0xc00018cc30, 0xc00025ba48)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	github.com/hashicorp/terraform@v0.12.6/helper/plugin/grpc_provider.go:1036 +0x46d
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadDataSource_Handler(0xfdb640, 0xc00000e4d0, 0x12735e0, 0xc00018cc30, 0xc000100a00, 0x0, 0x12735e0, 0xc00018cc30, 0xc0001b81b0, 0x23)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	github.com/hashicorp/terraform@v0.12.6/internal/tfplugin5/tfplugin5.pb.go:3253 +0x217
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001980, 0x127db80, 0xc000186780, 0xc0001a8600, 0xc00018c390, 0x19799d0, 0x0, 0x0, 0x0)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	google.golang.org/grpc@v1.18.0/server.go:966 +0x46a
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: google.golang.org/grpc.(*Server).handleStream(0xc000001980, 0x127db80, 0xc000186780, 0xc0001a8600, 0x0)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	google.golang.org/grpc@v1.18.0/server.go:1245 +0xc9e
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00052a5b0, 0xc000001980, 0x127db80, 0xc000186780, 0xc0001a8600)
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	google.golang.org/grpc@v1.18.0/server.go:685 +0xa1
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-12T16:10:59.986-0400 [DEBUG] plugin.terraform-provider-logzio_v1.1.8: 	google.golang.org/grpc@v1.18.0/server.go:683 +0xa1
2021-04-12T16:10:59.988-0400 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/logzio/logzio/1.1.8/linux_amd64/terraform-provider-logzio_v1.1.8 pid=67925 error="exit status 2"
2021/04/12 16:10:59 [ERROR] eval: *terraform.evalReadDataRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/04/12 16:10:59 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/04/12 16:10:59 [TRACE] [walkRefresh] Exiting eval tree: data.logzio_endpoint.slack
2021/04/12 16:10:59 [TRACE] vertex "data.logzio_endpoint.slack": visit complete
2021/04/12 16:10:59 [TRACE] vertex "data.logzio_endpoint.slack": dynamic subgraph encountered errors
2021/04/12 16:10:59 [TRACE] vertex "data.logzio_endpoint.slack": visit complete
2021/04/12 16:10:59 [TRACE] vertex "data.logzio_endpoint.slack (expand)": dynamic subgraph encountered errors
2021/04/12 16:10:59 [TRACE] vertex "data.logzio_endpoint.slack (expand)": visit complete
2021/04/12 16:10:59 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/logzio/logzio\"] (close)" errored, so skipping
2021/04/12 16:10:59 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/04/12 16:10:59 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/04/12 16:10:59 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-04-12T16:10:59.988-0400 [DEBUG] plugin: plugin exited
```

I am NOT a GO developer but looking at this

https://github.com/logzio/terraform-provider-logzio/blob/master/logzio/datasource_endpoint.go#L31

I changed it to:
`endpoint, err := client.GetEndpoint(int64(endpointId.(int)))`

and it works fine.

**Comment by jkowall** [comment]
Thanks @Veluu ! Do you want to submit the PR or shall I?

**Comment by Doron-Bargo** [comment]
Hi @Veluu do you still have error after this fix?

Thanks

**Comment by Veluu** [comment]
Hi @Doron-Bargo 

No, it works fine. The small change fixed the problem I experienced.
